### PR TITLE
Consistency fixups

### PR DESCRIPTION
**Pull request by RisinT96**
Tasmota calls this vendor, so we should stick to that.

### CODE REVIEW

**Comment by RisinT96** [comment]
Yeah I am aware of that.
Keeping the old parameter as an alias sounds like a good idea, I'll look into it.

Speaking of breaking changes, should probably start creating releases, with the whole semantic versioning stuff, this way people using the current version won't have their systems suddenly break unless they download the new release.

I could help set that up using github actions.

**Comment by RisinT96** [comment]
Okay now the users can use either `protocol` or `vendor` but not both.

The schema doesn't support making exclusive parameters mandatory, so I had to add a check+log in `async_setup_platform`, the log should show up on the server logs making it easy to detect if the user forgot to configure it.

**Comment by hristo-atanasov** [comment]
Ok. I see there are 3 pull requests. Which of them I should merge? All 3 of them or just this one?

**Comment by RisinT96** [comment]
> @RisinT96 Ok. I see there are 3 pull requests. Which of them I should merge? All 3 of them or just this one?

Well that depends on you :), if you think that the PRs are of any use, merge them.
I tested the code of both of my PRs on my hass instance and they seem to work as expected.

**Pull request merged**
