### PR TITLE
Added service to set vertical and horizontal vanes

### LINKED ISSUE #45: swing mode pasasonic
can you add swing mode vertical for panasonic

my panasonic airconditional have this mode for swing
Highest
High
Middle
Low
Lowest
Auto

the code for tasmota is

{"Vendor": "PANASONIC_AC", "Model": "-1", "Power": "on", "Mode": "dry", "Celsius": "on", "Temp": 23, "FanSpeed": "auto", "SwingV": "off", "SwingH": "off", "Quiet": "off", "Turbo": "off", "Econo": "off", "Light": "off", "Filter": "off", "Clean": "off", "Beep": "off", "Sleep": -1}

thank you

### PR DESCRIPTION
**Pull request by nao-pon**
This service allows setting wind direction using a selection helper.

This may resolve #45.

### CODE REVIEW

**Review by hristo-atanasov — COMMENTED** [review]
Hi, Nao! I was wondering why SwingH and SwingV are predefined in the array. Isn't it better to leave the user list its own AC supported swing modes. I mean, looking in Tasmota's code I can see lots of variations of SwingH. Or we can insert all values from Tasmota in the array.. See this link:
[IRtext.cpp](https://github.com/crankyoldgit/IRremoteESP8266/blob/ff045f149cbc2e31c8512169c1455578b8bf405e/src/IRtext.cpp#L174)

**Comment by nao-pon** [comment]
## Example

### Input Select Helper
- input_select helper as `input_select.living_ac_swingh`
- options:
```
  - 'off'
  - auto
  - left max
  - left
  - middle
  - right
  - right max
```

### Automation

- Target climate as `climate.living_ac`

```yaml
alias: Set AC SwingH
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.living_ac
    attribute: swingh
    id: get
  - platform: state
    entity_id:
      - input_select.living_ac_swingh
    id: set
condition: []
action:
  - if:
      - condition: trigger
        id: set
    then:
      - service: tasmota_irhvac.set_swingh
        data:
          entity_id: climate.living_ac
          swingh: "{{states(trigger.entity_id)}}"
    else:
      - service: input_select.select_option
        data:
          option: "{{state_attr(trigger.entity_id, 'swingh')}}"
        target:
          entity_id: input_select.living_ac_swingh
mode: parallel
max: 2
```

**Comment by nao-pon** [comment]
@hristo-atanasov Write it down as a memorandum.

Multiple terms are defined for the input to absorb differences in notation, but internally it is single and the output is also single.
Write it down as a memorandum.

Multiple terms are defined for the input to absorb differences in notation, but internally it is single and the output is also single.

- https://github.com/crankyoldgit/IRremoteESP8266/blob/ff045f149cbc2e31c8512169c1455578b8bf405e/src/IRsend.h#L69-L94
- https://github.com/crankyoldgit/IRremoteESP8266/blob/ff045f149cbc2e31c8512169c1455578b8bf405e/src/IRac.cpp#L3735-L3766

**Comment by nao-pon** [comment]
I also made a Blueprint that makes it easier to create automation.

ref. https://community.home-assistant.io/t/tasmota-mqtt-irhvac-controler/162915/404

**Pull request merged**
