### PR TITLE
Enhanced some options and features

### LINKED ISSUE #17: temp resets to zero when turning off the ac
hi.
ive noticed that temperature resets to 0 when i turn off one of my ac's.
i think its because the component sends the off command without temperature and the info it receives from MQTT (/tele/irblaster_name/RESULT) does not include actual temperature, so the component resets it to 0.

have i missed something in the configuration (possibly ignoring the temp when the command is "off") or is it a bug?

i really hope i made myself clear, although when i reread the post i'm not sure i quite understand it myself ;) anyways, if you need examples/logs/further explanations feel free to ask.
thanks.

### PR DESCRIPTION
**Pull request by nao-pon**
Create a PR that summarizes some extensions. It may be possible to resolve #17, #21, #22, #29, #45, #47 and #49.

@biGdada, @ayavilevich, @RobinSinghNanda, @bilogic, @riddik14, @angsanley, @rishabmehta7 and @hristo-atanasov, Please cooperate in the verification of this PR.

Download: https://github.com/nao-pon/Tasmota-IRHVAC/archive/refs/heads/various.zip

### Changes

1. Added options

```yaml
humidity_sensor: sensor.kitchen_humidity #optional - humidity sensor
power_sensor: binary_sensor.kitchen_ac_power #optional - power sensor (on/off)
default_swingv: "Off" #optional - default None string value
default_swingh: "Off" #optional - default None string value
```

2. Support MQTT availability feature via "LWT"

3. Supports swingV and swingH (Holds the information obtained from the
IR remote control.)

4. Keep as much as possible the various options (vertical vane, lights,
etc.) when operating with the original IR remote control in HA

5. Device statuses are restored to the original state when HA is
restarted.

6. Supports devices that can set the temperature in 0.5 increments

7. Supports Mitsubishi air conditioner weekly timers and older models of
Panasonic air conditioners.
    However, you need a customized Tasmota farm. You can get it from the
link below.
      - https://github.com/nao-pon/Tasmota/tree/irremote_full_custom
      - http://hypweb.net/tasmota/firmware/ir_jema_bridge.bin.gz
      - http://hypweb.net/tasmota/firmware/ir_jema_bridge_ccs811.bin.gz
        (With CCS811 sensor)

### CODE REVIEW

**Comment by rishabmehta7** [comment]
Working for me!!

Thanks :-)

**Comment by rishabmehta7** [comment]
We might want to use the button entity for some of the states. (turbo, eco, clean etc)

**Comment by hristo-atanasov** [comment]
At first look I see it does not work ok for ELECTRA_AC set_fan_mode .. I'll comment what should be changed when I find the fix. :) Once fixed it will be OK. :)

**Comment by hristo-atanasov** [comment]
OK .. I found the problem, but the issue started very long time ago and if it is working for the others, we can merge. I've made the initial commit with this bug, so not urgent. We can apply the fix later, before the release. :)

**Review by hristo-atanasov — APPROVED** [review]
Works well ..

**Comment by nao-pon** [comment]
@hristo-atanasov Thanks! 👍

**Comment by angsanley** [comment]
Can confirm, this PR fixes my issue #47. I'm closing my PR #48 now.

**Comment by hristo-atanasov** [comment]
> @hristo-atanasov Thanks! 👍

Many thanks to you @nao-pon! This would not be possible without your big collaboration! :)

**Comment by dobrishinov** [comment]
First many thanks to @hristo-atanasov for that amazing integration and many thanks to @nao-pon for the update!
Regarding point 3, could you please give me a little bit more info on how can I use default_swingv and default_swingh without hardcode the values in the config? I'm using the climate component. I saw there are some kinds of services like set_econo, set_turbo, etc. From what I understand with that services we can call that functions from buttons but are these valid for swingv, swingh?
Regarding point 4, is it possible to track changes from IR remote as well when we using the original remote controller? 
Thanks!

**Comment by hristo-atanasov** [comment]
@dobrishinov Hi! default_swingv and default_swingh are ment to be hardcoded in the config. I know this is an important feature, regarding being able to use swingv and swingh, but there is a small limitation in HA, that is stopping me to implement it in an easy to use way (for now). This is the reason we, or at least me, we don't have such services like set_swingv and set_swingh. Currently you can use their `auto` and `off` options via the `More info` -> `Swing mode` .

**Comment by nao-pon** [comment]
@dobrishinov Regarding point 4, when you send swingv and swingh with the IR remote controller (toward the IR receiver used in this integration), the values are stored internally. Since the stored swingv and swingh values are included in the subsequent transmission data, the state set by the IR remote controller is retained.

**Comment by dobrishinov** [comment]
> @dobrishinov Regarding point 4, when you send swingv and swingh with the IR remote controller (toward the IR receiver used in this integration), the values are stored internally. Since the stored swingv and swingh values are included in the subsequent transmission data, the state set by the IR remote controller is retained.

@nao-pon Great, so from my understanding, every time when we using the original remote controller, the data state for swing are automatically saved in the integration? Without needs to put some kind of different topics in the config I think, because the data stream are one from Tasmota. In that way is it possible easy to integrate some kind of feedback from the remote? If the temperature or other setting is changed, value to be updated in HA?

**Comment by nao-pon** [comment]
@dobrishinov First of all, it's machine translation, so I'm sorry if there is a mistranslation.

If HA can successfully receive the signal from the original remote control, the features supported by Tasmota are stored in HA.
For example, if you set the wind direction on the right side with the original remote control, the wind direction (to the right side) will not change even if you operate it with HA.

You can see the stored values in the status of the HA Developer Tools.

**Pull request merged**
