### PR TITLE
support CURRENT_HVAC_*

### PR DESCRIPTION
**Pull request by nao-pon**
By returning an appropriate value with hvac_action(), the icon color etc.
will be displayed properly in the UI.

### CODE REVIEW

**Comment by hristo-atanasov** [comment]
Please, tell me more about what problem does this PR solves!

**Comment by nao-pon** [comment]
Due to this PR, the color of the entity icon changes depending on the operation mode of the unit. It is orange when heating, light blue when cooling, and gray (default) when OFF. This allows you to see the status of the unit at a glance.

**Comment by hristo-atanasov** [comment]
Described functionality is working fine. No need of this PR. If you don't see colors use more recent version of the component. If this doesn't work again use color display instead of monochromatic one.

**Comment by nao-pon** [comment]
No, I tried with the latest components. The results are as follows.
icon_color_0

The results of applying this patch are as follows: Notice the change in the color of the icon.
icon_color

**Comment by hristo-atanasov** [comment]
Ok! I got it! I didn't even notice this icon until you posted these images. I'll open and accept the PR, but I'll make a small change, as we don't need all CURRENT_HVAC_* modes. We need only fan plus these finishing to "ing": heating, cooling and drying. Others are exactly the same like HVAC_MODE_*, so we just return the self._current_mode. Also we don't need to return None at the end, as self._current_mode is always one of the hvac modes.

**Comment by nao-pon** [comment]
@hristo-atanasov Thanks for your merge. Also, thank you for developing a great component!

**Pull request merged**
